version: '20.10.22'
services:
    container_name: postgres_container
    image: postgres
        environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=blog
      - POSTGRES_PASSWORD=123
      volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
    