version: '20.10.22'
services:
      app:
    container_name: blog
    image: blog
    build: ./
    ports:
      - 8080:8080
    depends_on:
      - postgres
    postgresqldb:
        image: postgres
        ports: 
       - "5432:5432"
        environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=blog
      - POSTGRES_PASSWORD=123
       