version: 'v20.10.22'
services:
  postgres:
    build: 
      dockerfile: Dockerfile.postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - "db-data:/var/lib/postgresql/data"
    
      
    build: 
      dockerfile: Dockerfile
    environment:
      - PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres/vv
    image: 'blog-docker'
    ports:
      - 8080:8080
    depends_on:
      - postgres